import type { FastifyInstance } from "fastify";
import { authRoutes } from "./auth/auth.routes.js";
import { eventsRoutes } from "./events/events.routes.js";
import { incidentsRoutes } from "./incidents/incidents.routes.js";
import { alertsRoutes } from "./alerts/alerts.routes.js";
import { copilotRoutes } from "./copilot/copilot.routes.js";
import { dashboardRoutes } from "./dashboard/dashboard.routes.js";
import { aiScoringRoutes } from "./ai-scoring/alert-priority.service.js";
import { searchRoutes } from "./search/search.routes.js";
import { notificationsRoutes } from "./notifications/notifications.routes.js";
import { websocketRoutes } from "./realtime/websocket.routes.js";
import { endpointsRoutes } from "./endpoints/endpoints.routes.js";
import { vulnerabilitiesRoutes } from "./vulnerabilities/vulnerabilities.routes.js";
import { threatIntelRoutes } from "./threat-intel/threat-intel.routes.js";
import { huntRoutes } from "./hunt/hunt.routes.js";
import { forensicsRoutes } from "./forensics/forensics.routes.js";
import { cloudRoutes } from "./cloud/cloud.routes.js";
import { networkRoutes } from "./network/network.routes.js";
import { knowledgeRoutes } from "./knowledge/knowledge.routes.js";
import { casesRoutes } from "./cases/cases.routes.js";
import { investigationsRoutes } from "./investigations/investigations.routes.js";
import { complianceRoutes } from "./compliance/compliance.routes.js";
import { reportsRoutes } from "./reports/reports.routes.js";
import { runbooksRoutes } from "./runbooks/runbooks.routes.js";
import { attackGraphRoutes } from "./attack-graph/attack-graph.routes.js";
import { auditRoutes } from "./audit/audit.routes.js";
import { platformHealthRoutes } from "./platform-health/platform-health.routes.js";
import { developerRoutes } from "./developer/developer.routes.js";
import { integrationsRoutes } from "./integrations/integrations.routes.js";
import { organizationsRoutes } from "./organizations/organizations.routes.js";
import { usersRoutes } from "./users/users.routes.js";
import { detectionRulesRoutes } from "./detection-rules/detection-rules.routes.js";
import { aiRoutes } from "./ai/ai.routes.js";
import { suppressionRulesRoutes } from "./alerts/suppression-rules.routes.js";
import { policiesRoutes } from "./policies/policies.routes.js";
import { notificationChannelsRoutes } from "./alerts/notification-channels.routes.js";
import { routingRulesRoutes } from "./alerts/routing-rules.routes.js";
import { escalationPoliciesRoutes } from "./alerts/escalation-policies.routes.js";

export async function registerApiRoutes(app: FastifyInstance) {
  await app.register(authRoutes);
  await app.register(eventsRoutes);
  await app.register(incidentsRoutes);
  await app.register(alertsRoutes);
  await app.register(copilotRoutes);
  await app.register(dashboardRoutes);
  await app.register(aiScoringRoutes);
  await app.register(searchRoutes);
  await app.register(notificationsRoutes);
  await app.register(websocketRoutes);
  await app.register(endpointsRoutes);
  await app.register(vulnerabilitiesRoutes);
  await app.register(threatIntelRoutes);
  await app.register(huntRoutes);
  await app.register(forensicsRoutes);
  await app.register(cloudRoutes);
  await app.register(networkRoutes);
  await app.register(knowledgeRoutes);
  await app.register(casesRoutes);
  await app.register(investigationsRoutes);
  await app.register(complianceRoutes);
  await app.register(reportsRoutes);
  await app.register(runbooksRoutes);
  await app.register(attackGraphRoutes);
  await app.register(auditRoutes);
  await app.register(platformHealthRoutes);
  await app.register(developerRoutes);
  await app.register(integrationsRoutes);
  await app.register(organizationsRoutes);
  await app.register(usersRoutes);
  await app.register(detectionRulesRoutes);
  await app.register(aiRoutes);
  await app.register(suppressionRulesRoutes);
  await app.register(policiesRoutes);
  await app.register(notificationChannelsRoutes);
  await app.register(routingRulesRoutes);
  await app.register(escalationPoliciesRoutes);
}