/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVulnerabilitiesRouteImport } from './routes/_app.vulnerabilities'
import { Route as AppThreatIntelligenceRouteImport } from './routes/_app.threat-intelligence'
import { Route as AppStatusRouteImport } from './routes/_app.status'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlatformHealthRouteImport } from './routes/_app.platform-health'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNetworkRouteImport } from './routes/_app.network'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppInvestigationsRouteImport } from './routes/_app.investigations'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppIncidentsRouteImport } from './routes/_app.incidents'
import { Route as AppIdentityRouteImport } from './routes/_app.identity'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppEndpointsRouteImport } from './routes/_app.endpoints'
import { Route as AppDeveloperRouteImport } from './routes/_app.developer'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppCloudSecurityRouteImport } from './routes/_app.cloud-security'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAttackGraphRouteImport } from './routes/_app.attack-graph'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppIncidentsIncidentIdRouteImport } from './routes/_app.incidents.$incidentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVulnerabilitiesRoute = AppVulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatIntelligenceRoute = AppThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformHealthRoute = AppPlatformHealthRouteImport.update({
  id: '/platform-health',
  path: '/platform-health',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppEndpointsRoute = AppEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCloudSecurityRoute = AppCloudSecurityRouteImport.update({
  id: '/cloud-security',
  path: '/cloud-security',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackGraphRoute = AppAttackGraphRouteImport.update({
  id: '/attack-graph',
  path: '/attack-graph',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIncidentIdRoute = AppIncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => AppIncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/attack-graph': typeof AppAttackGraphRoute
  '/audit': typeof AppAuditRoute
  '/cases': typeof AppCasesRoute
  '/cloud-security': typeof AppCloudSecurityRoute
  '/compliance': typeof AppComplianceRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/developer': typeof AppDeveloperRoute
  '/endpoints': typeof AppEndpointsRoute
  '/events': typeof AppEventsRoute
  '/identity': typeof AppIdentityRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/integrations': typeof AppIntegrationsRoute
  '/investigations': typeof AppInvestigationsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/network': typeof AppNetworkRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/organizations': typeof AppOrganizationsRoute
  '/platform-health': typeof AppPlatformHealthRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/status': typeof AppStatusRoute
  '/threat-intelligence': typeof AppThreatIntelligenceRoute
  '/vulnerabilities': typeof AppVulnerabilitiesRoute
  '/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/attack-graph': typeof AppAttackGraphRoute
  '/audit': typeof AppAuditRoute
  '/cases': typeof AppCasesRoute
  '/cloud-security': typeof AppCloudSecurityRoute
  '/compliance': typeof AppComplianceRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/developer': typeof AppDeveloperRoute
  '/endpoints': typeof AppEndpointsRoute
  '/events': typeof AppEventsRoute
  '/identity': typeof AppIdentityRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/integrations': typeof AppIntegrationsRoute
  '/investigations': typeof AppInvestigationsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/network': typeof AppNetworkRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/organizations': typeof AppOrganizationsRoute
  '/platform-health': typeof AppPlatformHealthRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/status': typeof AppStatusRoute
  '/threat-intelligence': typeof AppThreatIntelligenceRoute
  '/vulnerabilities': typeof AppVulnerabilitiesRoute
  '/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/attack-graph': typeof AppAttackGraphRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/cloud-security': typeof AppCloudSecurityRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/developer': typeof AppDeveloperRoute
  '/_app/endpoints': typeof AppEndpointsRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/identity': typeof AppIdentityRoute
  '/_app/incidents': typeof AppIncidentsRouteWithChildren
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/investigations': typeof AppInvestigationsRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/platform-health': typeof AppPlatformHealthRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/threat-intelligence': typeof AppThreatIntelligenceRoute
  '/_app/vulnerabilities': typeof AppVulnerabilitiesRoute
  '/_app/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/alerts'
    | '/attack-graph'
    | '/audit'
    | '/cases'
    | '/cloud-security'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/developer'
    | '/endpoints'
    | '/events'
    | '/identity'
    | '/incidents'
    | '/integrations'
    | '/investigations'
    | '/knowledge'
    | '/network'
    | '/notifications'
    | '/onboarding'
    | '/organizations'
    | '/platform-health'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/status'
    | '/threat-intelligence'
    | '/vulnerabilities'
    | '/incidents/$incidentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/alerts'
    | '/attack-graph'
    | '/audit'
    | '/cases'
    | '/cloud-security'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/developer'
    | '/endpoints'
    | '/events'
    | '/identity'
    | '/incidents'
    | '/integrations'
    | '/investigations'
    | '/knowledge'
    | '/network'
    | '/notifications'
    | '/onboarding'
    | '/organizations'
    | '/platform-health'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/status'
    | '/threat-intelligence'
    | '/vulnerabilities'
    | '/incidents/$incidentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/landing'
    | '/login'
    | '/_app/alerts'
    | '/_app/attack-graph'
    | '/_app/audit'
    | '/_app/cases'
    | '/_app/cloud-security'
    | '/_app/compliance'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/developer'
    | '/_app/endpoints'
    | '/_app/events'
    | '/_app/identity'
    | '/_app/incidents'
    | '/_app/integrations'
    | '/_app/investigations'
    | '/_app/knowledge'
    | '/_app/network'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/organizations'
    | '/_app/platform-health'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/status'
    | '/_app/threat-intelligence'
    | '/_app/vulnerabilities'
    | '/_app/incidents/$incidentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vulnerabilities': {
      id: '/_app/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof AppVulnerabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threat-intelligence': {
      id: '/_app/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof AppThreatIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform-health': {
      id: '/_app/platform-health'
      path: '/platform-health'
      fullPath: '/platform-health'
      preLoaderRoute: typeof AppPlatformHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations': {
      id: '/_app/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof AppInvestigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/identity': {
      id: '/_app/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endpoints': {
      id: '/_app/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof AppEndpointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cloud-security': {
      id: '/_app/cloud-security'
      path: '/cloud-security'
      fullPath: '/cloud-security'
      preLoaderRoute: typeof AppCloudSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-graph': {
      id: '/_app/attack-graph'
      path: '/attack-graph'
      fullPath: '/attack-graph'
      preLoaderRoute: typeof AppAttackGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$incidentId': {
      id: '/_app/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AppIncidentsIncidentIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
  }
}

interface AppIncidentsRouteChildren {
  AppIncidentsIncidentIdRoute: typeof AppIncidentsIncidentIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIncidentIdRoute: AppIncidentsIncidentIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAttackGraphRoute: typeof AppAttackGraphRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCasesRoute: typeof AppCasesRoute
  AppCloudSecurityRoute: typeof AppCloudSecurityRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppEndpointsRoute: typeof AppEndpointsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvestigationsRoute: typeof AppInvestigationsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppPlatformHealthRoute: typeof AppPlatformHealthRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatusRoute: typeof AppStatusRoute
  AppThreatIntelligenceRoute: typeof AppThreatIntelligenceRoute
  AppVulnerabilitiesRoute: typeof AppVulnerabilitiesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAttackGraphRoute: AppAttackGraphRoute,
  AppAuditRoute: AppAuditRoute,
  AppCasesRoute: AppCasesRoute,
  AppCloudSecurityRoute: AppCloudSecurityRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeveloperRoute: AppDeveloperRoute,
  AppEndpointsRoute: AppEndpointsRoute,
  AppEventsRoute: AppEventsRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppPlatformHealthRoute: AppPlatformHealthRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatusRoute: AppStatusRoute,
  AppThreatIntelligenceRoute: AppThreatIntelligenceRoute,
  AppVulnerabilitiesRoute: AppVulnerabilitiesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
